version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date      
      
      - run:
          name: Run npm install
          working_directory: ~/mslearn-tailspin-spacegame-web
          command: npm install