version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date      
      
      - run:
          name: Installing npm on the docker
          command: apt-get update -yq  
      - run:     
           command: apt-get install curl gnupg -yq
      - run:
          command: curl -sL https://deb.nodesource.com/setup_8.x | bash
      - run: 
          command: apt-get install nodejs -yq

      - run: 
          name: what is here
          command: ls
      - run:
          name: Run npm install
          working_directory: ~/mslearn-tailspin-spacegame-web
          command: npm install